### ISSUE TITLE
Can't run YAML config file in local directory

### ISSUE THREAD

**Issue by maximecb** [MillionIntegrals/vel#30]
I installed vel through pip, and then downloaded one of the example YAML config files so I could modify it. However, I can't seem to get the launcher to run a config file from the current directory, and I'm not sure why:

```
maxime@Desktop:~/Desktop/gym-miniworld$ ls -al
...
-rw-rw-r-- 1 maxime maxime 1636 Nov 21 15:23 breakout_ppo.yaml

 vel breakout_ppo.yaml train
Traceback (most recent call last):
  File "/home/maxime/.local/bin/vel", line 11, in <module>
    sys.exit(main())
  File "/home/maxime/.local/lib/python3.6/site-packages/vel/launcher.py", line 30, in main
    params={k: v for (k, v) in (Parser.parse_equality(eq) for eq in args.param)}
  File "/home/maxime/.local/lib/python3.6/site-packages/vel/api/model_config.py", line 39, in from_file
    project_config_path = ModelConfig.find_project_directory(os.path.dirname(os.path.abspath(filename)))
  File "/home/maxime/.local/lib/python3.6/site-packages/vel/api/model_config.py", line 31, in find_project_directory
    return ModelConfig.find_project_directory(up_path)
  File "/home/maxime/.local/lib/python3.6/site-packages/vel/api/model_config.py", line 31, in find_project_directory
    return ModelConfig.find_project_directory(up_path)
  File "/home/maxime/.local/lib/python3.6/site-packages/vel/api/model_config.py", line 31, in find_project_directory
    return ModelConfig.find_project_directory(up_path)
  File "/home/maxime/.local/lib/python3.6/site-packages/vel/api/model_config.py", line 29, in find_project_directory
    raise RuntimeError(f"Couldn't find project file starting from {start_path}")
RuntimeError: Couldn't find project file starting from /
```

Also tried the following, which also fail in the same way:
```
vel ./breakout_ppo.yaml train
python3 -m vel.launcher breakout_ppo.yaml train
python3 -m vel.launcher ./breakout_ppo.yaml train
```

**Comment by MillionIntegrals** [comment]
Thank you for the interest in this project!

There is one think I just realized I didn't put in the README, but I'll update it soon. To run the model, one needs YAML configuration of the model (like the one you're trying to run) and additionally a *project* configuration containing share configuration for the whole project.

This file is called `.velproject.yaml` and current default implementation configures it to store metrics in MongoDB and to use Visdom:

```yaml
storage:
  name: vel.storage.classic

  backend:
    name: vel.storage.backend.mongodb
    uri: 'mongodb://localhost:27017/'
    database: deep_learning

  streaming:
    - name: vel.storage.streaming.visdom
    - name: vel.storage.streaming.stdout


checkpoint_strategy:
  name: vel.storage.strategy.classic_checkpoint_strategy


visdom_settings:
  stream_lr: false
  server: 'http://localhost'
  port: 8097
```

In case you don't want that, I've added also a simple file that does not have any extra dependencies, but then does not store anything for later inspection, only writes to stdout:

```yaml
storage:
  name: vel.storage.classic

  backend:
    name: vel.storage.backend.dummy

  streaming:
    - name: vel.storage.streaming.stdout


checkpoint_strategy:
  name: vel.storage.strategy.classic_checkpoint_strategy
```

There are also a few examples in the `examples-scripts` directory about how to run models without yaml configs, just using script files, although I'm using that less myself so that could be a bit less fleshed out.

Let me know if you need to know anything more and in the meantime, I'll update REAME to be a bit clearer when I have some time.

**Comment by MillionIntegrals** [comment]
One extra remark is that while project is under active development, pip version is a bit out of date compared to the latest repository version. I'll probably release a new pip version soon, but for now I think it's the best to just checkout the repo and install locally using `pip install -e .`.

**Comment by maximecb** [comment]
After installing with `pip3 install -e .`, I'm trying to launch the breakout_ppo sample, and I get:

```
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```

Is there a way to not run with visdom or mongo? I just want to display learning progress in the console, and I'd rather not have to spawn extra services everytime I want to train something.

**Comment by MillionIntegrals** [comment]
Yeah, that's for mongo connection. To disable that use the other velproject file that I included above. That is, put the following contents into your `.velproject.yaml':



```yaml
storage:
  name: vel.storage.classic

  backend:
    name: vel.storage.backend.dummy

  streaming:
    - name: vel.storage.streaming.stdout


checkpoint_strategy:
  name: vel.storage.strategy.classic_checkpoint_strategy
```

That disables both Visdom and MongoDb, only leaves stdout

**Comment by maximecb** [comment]
I'm trying to edit the breakout PPO example to load a custom environment package. It seems to import the package, but then produces this error:

```
Traceback (most recent call last):
  File "/home/maximecb/.local/bin/vel", line 11, in <module>
    load_entry_point('vel', 'console_scripts', 'vel')()
  File "/home/maximecb/Desktop/vel/vel/launcher.py", line 39, in main
    model_config.run_command(args.command, args.varargs)
  File "/home/maximecb/Desktop/vel/vel/api/model_config.py", line 119, in run_command
    command_descriptor = self.get_command(command_name)
  File "/home/maximecb/Desktop/vel/vel/api/model_config.py", line 115, in get_command
    return self.provider.instantiate_from_data(self.command_descriptors[command_name])
  File "/home/maximecb/Desktop/vel/vel/internals/provider.py", line 57, in instantiate_from_data
    return self.resolve_and_call(module.create, extra_env=object_data)
  File "/home/maximecb/Desktop/vel/vel/internals/provider.py", line 41, in resolve_and_call
    kwargs[parameter_name] = self.instantiate_by_name(parameter_name)
  File "/home/maximecb/Desktop/vel/vel/internals/provider.py", line 88, in instantiate_by_name
    instance = self.instantiate_from_data(self.environment[object_name])
  File "/home/maximecb/Desktop/vel/vel/internals/provider.py", line 57, in instantiate_from_data
    return self.resolve_and_call(module.create, extra_env=object_data)
  File "/home/maximecb/Desktop/vel/vel/internals/provider.py", line 41, in resolve_and_call
    kwargs[parameter_name] = self.instantiate_by_name(parameter_name)
  File "/home/maximecb/Desktop/vel/vel/internals/provider.py", line 88, in instantiate_by_name
    instance = self.instantiate_from_data(self.environment[object_name])
  File "/home/maximecb/Desktop/vel/vel/internals/provider.py", line 57, in instantiate_from_data
    return self.resolve_and_call(module.create, extra_env=object_data)
  File "/home/maximecb/Desktop/vel/vel/internals/provider.py", line 41, in resolve_and_call
    kwargs[parameter_name] = self.instantiate_by_name(parameter_name)
  File "/home/maximecb/Desktop/vel/vel/internals/provider.py", line 88, in instantiate_by_name
    instance = self.instantiate_from_data(self.environment[object_name])
  File "/home/maximecb/Desktop/vel/vel/internals/provider.py", line 57, in instantiate_from_data
    return self.resolve_and_call(module.create, extra_env=object_data)
AttributeError: module 'gym_miniworld' has no attribute 'create'
```

Vel expects OpenAI Gym packages to have a create method?

**Comment by MillionIntegrals** [comment]
This is about how things are provided through config files to the actual algorithms. Generally, every module referenced in the config file is supposed to have a `create` method, which is the entry point called by the config. Additionally, what a create method for enviornments is supposed to return is an `EnvFactory` rather than an environment instance itself, as the algorithm may want to create multiple instances, variants etc.

An examples you can find in `vel/vel/rl/env/classic_atari.py`.

Minimum example package that includes custom environment looks kind of like that. (I didn't proofrun it but it should work)


```python
from vel.rl.api.base import EnvFactory

class MyEnvFactory(EnvFactory):
  def __init__(param1, param2):
    self.param1 = param1
    self.param2 = param2

  def instantiate(self, seed=0, serial_id=0, preset='default', extra_args=None):
     """ The actual method that instantiates your environment """
    return create_my_environment(self.param1, self.param2, seed=seed+serial_id, ...)


def create(param1, param2):
  return MyEnvFactory(param1, param2)

```

Let me know if you managed to get it right. Usually in the model you also need to adjust some parameters so that the input size it expects matches the observation output of your environment.

**Comment by MillionIntegrals** [comment]
I took some time to check out your projects and I must say I love the environments you've implemented. This is a very useful work that I'll definitely use in some of my projects.

Unfortunately, while vel is still basically my hobby project that I do in my free time, I'm unable to provide extensive and up to date documentation. What I'll try to do is open source as many examples of me using it in various contexts so that anyone interested can dig into them.

I've implemented a simple project with quick and dirty way to run ppo one some of your simple gridworld environments and it seems to work: https://github.com/MillionIntegrals/vel-miniworld

I'm still trying to make LSTM policy work on the doorkey env, if I get that working I'll commit it there as well. 

Unfortunately I'm not able to run the Miniworld Hallway environment, I get the following error:

```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 94 requests (94 known processed) with 0 events remaining.
```

probably some problems with initializing the OpenGL context, maybe I'll look into that more later...

**Comment by maximecb** [comment]
Oh cool. Thanks for taking the time to try it I'm very interested if you can get it working with the 3D MiniWorld envs. I know it's not easy to maintain an open source project. I try to put myself in the shoes of people first trying the project and lower the bar as much as possible, but there will always be issues.

Regarding that error, it could either be that you need to run a virtual display (if you're running through SSH). You can use `xvfb-run` for that: https://github.com/maximecb/gym-miniworld/blob/master/docs/troubleshooting.md#nosuchdisplayexception-cannot-connect-to-none

Or it might be due to multiprocessing, forking new processes. The process start method needs to be set to`forkserver` on Linux: https://github.com/maximecb/gym-miniworld/blob/master/pytorch-a2c-ppo-acktr/vec_env/subproc_vec_env.py#L39

**Comment by MillionIntegrals** [comment]
Yes, it was indeed a `forkserver` issue. I had to make a few adjustments here and there so that it works smoothly, and I think it does now.

There are some warnings during shutdown, it seems like the somewhere between the env and SubprocVecEnv something goes wrong but it's not a showstopper in any way.

Feel free to check out the configuration https://github.com/MillionIntegrals/vel-miniworld
I've also released 0.2.2 version of vel into pip with all the changes that were needed to make it work.

Let me know if you manage to get it running on your side as well.

**Comment by maximecb** [comment]
Thanks for taking the time to do this.

I tried to install the virtualenv and ran into some errors:
```
maxime@Desktop:~/Desktop/vel-miniworld$ pipenv install
Creating a virtualenv for this project…
Pipfile: /home/maxime/Desktop/vel-miniworld/Pipfile
Using /usr/bin/python3 (3.6.7) to create virtualenv…
⠧ Creating virtual environment...Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/maxime/.local/share/virtualenvs/vel-miniworld-u0sMizvc/bin/python3
Also creating executable in /home/maxime/.local/share/virtualenvs/vel-miniworld-u0sMizvc/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment! 
Virtualenv location: /home/maxime/.local/share/virtualenvs/vel-miniworld-u0sMizvc
Installing dependencies from Pipfile.lock (e84ec5)…
Ignoring atari-py: markers 'extra == "atari"' don't match your environment
Ignoring box2d-py: markers 'extra == "box2d"' don't match your environment
Ignoring dnspython: markers 'extra == "mongo"' don't match your environment
An error occurred while installing pandas==0.23.4 --hash=sha256:11975fad9edbdb55f1a560d96f91830e83e29bed6ad5ebf506abda09818eaf60 --hash=sha256:12e13d127ca1b585dd6f6840d3fe3fa6e46c36a6afe2dbc5cb0b57032c902e31 --hash=sha256:1c87fcb201e1e06f66e23a61a5fea9eeebfe7204a66d99df24600e3f05168051 --hash=sha256:242e9900de758e137304ad4b5663c2eff0d798c2c3b891250bd0bd97144579da --hash=sha256:26c903d0ae1542890cb9abadb4adcb18f356b14c2df46e4ff657ae640e3ac9e7 --hash=sha256:2e1e88f9d3e5f107b65b59cd29f141995597b035d17cc5537e58142038942e1a --hash=sha256:31b7a48b344c14691a8e92765d4023f88902ba3e96e2e4d0364d3453cdfd50db --hash=sha256:4fd07a932b4352f8a8973761ab4e84f965bf81cc750fb38e04f01088ab901cb8 --hash=sha256:5b24ca47acf69222e82530e89111dd9d14f9b970ab2cd3a1c2c78f0c4fbba4f4 --hash=sha256:647b3b916cc8f6aeba240c8171be3ab799c3c1b2ea179a3be0bd2712c4237553 --hash=sha256:66b060946046ca27c0e03e9bec9bba3e0b918bafff84c425ca2cc2e157ce121e --hash=sha256:6efa9fa6e1434141df8872d0fa4226fc301b17aacf37429193f9d70b426ea28f --hash=sha256:be4715c9d8367e51dbe6bc6d05e205b1ae234f0dc5465931014aa1c4af44c1ba --hash=sha256:bea90da782d8e945fccfc958585210d23de374fa9294a9481ed2abcef637ebfc --hash=sha256:d318d77ab96f66a59e792a481e2701fba879e1a453aefeebdb17444fe204d1ed --hash=sha256:d785fc08d6f4207437e900ffead930a61e634c5e4f980ba6d3dc03c9581748c7 --hash=sha256:de9559287c4fe8da56e8c3878d2374abc19d1ba2b807bfa7553e912a8e5ba87c --hash=sha256:f4f98b190bb918ac0bc0e3dd2ab74ff3573da9f43106f6dba6385406912ec00f --hash=sha256:f71f1a7e2d03758f6e957896ed696254e2bc83110ddbc6942018f1a232dd9dad --hash=sha256:fb944c8f0b0ab5c1f7846c686bc4cdf8cde7224655c12edcd59d5212cd57bec0! Will try again.
Ignoring pillow: markers 'extra == "atari"' don't match your environment
Ignoring pymongo: markers 'extra == "mongo"' don't match your environment
Ignoring pyopengl: markers 'extra == "atari"' don't match your environment

An error occurred while installing torchvision==0.2.1 --hash=sha256:ba0a5e7fa1646d4e7f2e5ad5802d123e17e42a1a9c026d0f79d2fd3a976afba1! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 37/37 — 00:01:59
An error occurred while installing vel[gym,mongo,visdom]==0.2.1 --hash=sha256:989cf3e855cedd39d4b51d9ce19b3a87c61273cf3f40fd23d0bfc8c226ca517c --hash=sha256:a61a4569fcdc59b17d1a9a5d24b46df36f9e1693df5e29b7d67c77223e90c4cb! Will try again.
Ignoring visdom: markers 'extra == "visdom"' don't match your environment
Installing initially failed dependencies…
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:03
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

I still tried to run a training command inside the shell, but got the following, possibly because the install didn't work correctly:
```
vel examples-configs/ppo/ppo_miniworld_hallway.yaml train
...
ModuleNotFoundError: No module named 'vel_miniworld'
```

**Comment by yngtodd** [comment]
Hope you don't mind me jumping in, but I saw this and got curious. When installing through `pipenv`, I ran into the same issue that @maximecb hit. I haven't had much experience with `Pipfile`s, but I was able to get around the issue by creating a quick and dirty `setup.py` file for `vel-miniworld`. With that my `vel` configuration worked great with @maximecb's environments:
```
🔥 vel-miniworld [master] 🍂  vel examples-configs/ppo/ppo_minigrid_empty_8x8.yaml train
<ModelConfig at examples-configs/ppo/ppo_minigrid_empty_8x8.yaml>
================================================================================
Pytorch version: 0.4.1 cuda version 9.0.176 cudnn version 7102
Running model ppo_minigrid_empty_8x8, run 0 -- command train -- device cuda
CUDA Device name Quadro P620
2018/11/25 - 14:48:33
================================================================================
Logging to /home/ygx/dev/nykyinen/vel-miniworld/output/openai/ppo_minigrid_empty_8x8/0
Training: 100%|████████████████████████████████████████████████████████████████████████████| 10/10 [00:08<00:00,  1.19batch/s]
=>>>>>>>>>> EPOCH 1 [ppo_minigrid_empty_8x8/0]
Metrics:   advantage_norm 15.968719 approx_kl_divergence 0.014062 clip_fraction 0.434180 episode_length 99.536082 epoch_idx 1.000000 explained_variance -0.446991 fps 1246.000000 frames 10240.000000 grad_norm 18.170809 policy_entropy 1.449126 policy_loss 0.010845 value_loss 0.489289
P01:       episode_rewards 0.000000
P09:       episode_rewards 0.000000
Pmm:       episode_rewards 0.045039
=>>>>>>>>>> DONE
Training:  20%|███████████████▍                                                             | 2/10 [00:01<00:06,  1.28batch/s]
```

**Comment by yngtodd** [comment]
I am sure that you would prefer the `pipenv` method in the long run. But, in case you want to get up and running quickly, here is the `setup.py` file that I used:
```
from setuptools import setup, find_packages

setup(
    name='vel-miniworld',
    version='0.0.1',
    description="miniworld for vel research",
    url='https://github.com/MillionIntegrals/vel-miniworld',
    author='Jerry Tworek',
    author_email='jerry@millionintegrals.com',
    license='MIT',
    python_requires='>=3.6',
    entry_points={
        'console_scripts': [
            'vel = vel.launcher:main',
        ],
    },
    scripts=[]
)
```
Then I installed through `python setup.py develop`.

**Comment by MillionIntegrals** [comment]
Hi @yngtodd, thank you for help. 

I think indeed there is a problem with with running examples via the `vel` script that @maximecb has seen, it is related to PYTHONPATH and how it is populated..

There are multiple ways to work around that:
1. Write simple setup.py for vel-miniworld and install locally, like @yngtodd did
2. I just pushed a new commit for vel that should solve the problem, adding missing directory to PYTHONPATH, but then you need to install newest master git checkout of vel to have that fix
3. Instead of running the example using the `vel` script:
```
vel examples-configs/ppo/ppo_miniworld_hallway.yaml train
```
Execute it using the python module run syntax:
```
python -m vel.launcher examples-configs/ppo/ppo_miniworld_hallway.yaml train
```

All of these solutions work for me.

**Comment by maximecb** [comment]
I was able to get it to work thanks to your suggestions. Seems the install process for vel is also smoother now :+1: (tried it on another machine).

**Comment by maximecb** [comment]
Are the episode rewards displayed in the console the average current reward? Is there a way to interactively view the result of training, as opposed to rendering a video?

**Comment by MillionIntegrals** [comment]
The rewards you see displayed during training:
```
P01:       episode_rewards 0.000000
P09:       episode_rewards 0.748080
Pmm:       episode_rewards 0.107867
```
Are a respectively 10% quantile, 90% quantile and a mean of total reward for last 100 of finished episodes. In other words we take last 100 episodes encountered during training from start to finish, sum their rewards through time and then they form a distribution. Out of that distribution I calculate mean and two quantiles.

Currently two ways to inspect an agent that was trained are:
- Evaluating the rewards it gets 
- Recording a video of an episode

What else do you have in mind?

**Comment by MillionIntegrals** [comment]
It took some time, but I've just release a new version, that has an `enjoy.py` command ;)
