### ISSUE TITLE
How do models deal with environments with no scale_float_frames?

### ISSUE THREAD

**Issue by phizaz** [MillionIntegrals/vel#47]
In `classic_atari.py`, there is an option `scale_float_frames` which is `False` be default. I think this is to reduce the memory usage (a byte is smaller than a float). I wonder if that is the case there must be a scaling somewhere else, but I have yet to find it. Would you also elaborate more on the structure of relevant classes? Keywords are hard to get by intuition.

**Comment by MillionIntegrals** [comment]
Your intuitions are right there.

- `scale_float_frames` means that 8-bit (byte) atari grayscale images taking values between 0 and 255 will be scaled into 32-bit floating point numbers between 0.0 and 1.0. This is a suitable input for a neural network, but also takes 4 times more memory
- Therefore, especially when using a replay buffer (which often takes a lot of memory, on the order of gigabytes even for simple DQN learning) we take observations as smaller byte arrays, store them as such in the replay buffer and then sample them like that from the replay buffer into the observation of the neural net
- But, just like you've said since networks in general take floating point inputs, this scaling must be done somewhere. It is done in this simple module called `vel.module.input.image_to_tensor`. It's definition is rather brief:

```
class ImageToTensor(BackboneModel):
    """
    Convert simple image to tensor.

    Flip channels to a [C, W, H] order and potentially convert 8-bit color values to floats
    """

    def __init__(self):
        super().__init__()

    def reset_weights(self):
        pass

    def forward(self, image):
        result = image.permute(0, 3, 1, 2).contiguous()

        if result.dtype == torch.uint8:
            result = result.type(torch.float) / 255.0
        else:
            result = result.type(torch.float)

        return result
```

It is configured in the model section in the yaml config, as an example here:

```
model:
  name: vel.rl.models.q_model

  input_block:
    name: vel.modules.input.image_to_tensor

  backbone:
    name: vel.rl.models.backbone.nature_cnn
    input_width: 84
    input_height: 84
    input_channels: 4  # The same as frame_history
```

In general, I tried to factor each model in such way that they have a "input block" that maps whatever input the neural network receives into actual floating point number array of the right shape so that later it can be used in transformation downstream.

Let me know if you have any other questions.

**Comment by phizaz** [comment]
@MillionIntegrals It seems that `image_to_tensor` is safe to use regardless of the flag of the environment?

**Comment by MillionIntegrals** [comment]
Yes, it just happens in a different stage of processing. If you'd like to have something between the env and a network that needs floating point inputs then it's good to set `scale_float_frames` to true, otherwise it's not needed.
